config/routes.rb
Rails.application.routes.draw do
  resource :companies 
  resource :company_session 
  put 'credit_lines/:id' => 'credit_lines#update'
  resources :credit_lines

  resources :credits 
  get 'company/:url/signup' => "credits#new"  

  root to: 'start#index'

  resources :clientes
  get 'empresa/:empresa_url/signup' => "clientes#new"
  

end

app/models/credit_line.rb
class CreditLine
  include MongoMapper::Document

  key :name, String
  key :anual_rate, Float
  key :url, String
  key :state, String

  validates :name, :length=> {maximum: 50}, :presence=>true
  validates :anual_rate, presence: true, 
  	numericality: {greater_than: 0, less_than: 100}
  validates :url, presence: true

  before_create :set_state

  def set_state
    self.state = 'active'
  end

  def company
    @company||=Company.where(url: self.url).first
  end
end

app/controllers/credit_lines_controller.rb
class CreditLinesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_model, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @collection = CreditLine.where(url: current_company_url).where(state: 'active').all
  end

  def show
    redirect_to credit_lines_path
  end
  
  def new
    @object = CreditLine.new
    respond_with(@object)
  end

  def edit
    respond_with(@object)
  end

  def create
    @object= CreditLine.new(get_params)
    @object.url = current_company_url
    @object.save
    respond_with(@object)
  end

  def update
    @object.attributes=@object.attributes.update(get_params.symbolize_keys)
    if @object.save
      redirect_to credit_lines_path
    else
      render 'edit'
    end
  end

  def destroy
   # @object.destroy
    #No elimina, solo desactiva
    
    @object.state = 'disabled'
    @object.save
    respond_with(@object, :location=> credit_lines_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @object = CreditLine.find(params[:id], :consistent_read => true)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def get_params
      params.require(:credit_line).permit(:name, :anual_rate)
    end

    def get_fields
      %w{name anual_rate}
    end
end

app/helpers/credit_lines_helper.rb
module CreditLinesHelper
end

app/views/credit_lines/_form.html.erb
<%= simple_form_for(@object) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name%>
    <%= f.input :anual_rate%>
  </div>

  <div class="form-actions">
    <%= f.button(:submit) %>
    <%= bs_button_to t(:cancel), credit_lines_path,
      style: "inverse" %>
  </div>
<% end %>

app/views/credit_lines/_row.html.erb
<tr id=<%= dom_id(row)%> >
  <% get_fields[0..-1].each do |field| %>
  <td>
    <%= row.send(field) -%>
  </td>
  <%end%>
  <td class='action-cell'>
    <%= link_to('Editar', edit_credit_line_path(row))%>
    <%= link_to('Elminar',credit_line_path(row), method: :delete, 
        data: {confirm: 'Desea eliminar?'}) %>
  </td>
</tr>

app/views/credit_lines/edit.html.erb
<div class="page-header">
  <h1> Editar crédito</h1>
</div>
<%= simple_form_for(@object, url: "/credit_lines/#{@object.id}", method: :put ) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name%>
    <%= f.input :anual_rate%>
  </div>

  <div class="form-actions">
    <%= f.button(:submit) %>
    <%= bs_button_to t(:cancel), credit_lines_path,
      style: "inverse" %>
  </div>
<% end %>

app/views/credit_lines/index.html.erb
<% content_for :title do %>
  Líneas de crédito
  <small>
    <i class="icon-double-angle-right"></i>
    
  </small>
<% end %>
<div class='dataTables_wrapper' role='grid'>
  <div class="row">
      <div class="col-sm-6">
        <div class="dataTables_info" id="functions_panel">
          <%= bs_button_to(t(:register), new_credit_line_path, icon: "plus", 
            style: "success", size: 'sm') %>
        </div>
      </div>
  </div>
</div>
<table id="index_table" class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <% get_fields.each do |field| %>
        <th>
          <%=(field)%>
        </th>
      <% end %>
      <th ></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'row', collection: @collection %> 
  </tbody>
</table>
<div class="row">
  <div class="col-sm-6">
    <div class="dataTables_info" id="paginate_total_info">
      
    </div>
  </div>
  <div class="col-sm-6">
    <div class="dataTables_paginate paging_bootstrap" id="paginate_links">
      
    </div>
  </div>
</div>

app/views/credit_lines/new.html.erb
<div class="page-header">
  <h1> Crear línea de crédito</h1>
</div>
<%= render partial: 'form' %>