config/routes.rb
Rails.application.routes.draw do
  resource :companies 
  resource :company_session 
  put 'credit_lines/:id' => 'credit_lines#update'
  resources :credit_lines

  resources :credits 
  get 'company/:url/signup' => "credits#new"  

  root to: 'start#index'

  resources :clientes
  get 'empresa/:empresa_url/signup' => "clientes#new"
  

end

app/models/credit.rb
class Credit
  include MongoMapper::Document

  key :identification, String
  key :birthday, DateTime
  key :amount, Integer
  key :months, Integer
  key :url, String
  key :credit_line_id, ObjectId
  key :credit_line_name, String
  key :credit_line_anual_rate, Float
  key :state, String
  key :risk, Float
  key :total_payment, Float
  key :total_interest, Float
  key :created_at, DateTime
  key :timestamp, Integer
  key :payments, Array

  validates :identification, presence: true, length: { in: 1..50 }
  validates :birthday, presence: true
  validates :amount, presence: true, numericality: {greater_than: 0}
  validates :months, presence: true, numericality: {greater_than: 0, integer: true}
  validates :url, presence: true
  validates :credit_line_id, presence: true

  before_create do |obj|
    obj.state = 'pending'
    obj.created_at=DateTime.now
    obj.timestamp=10.gigabyte-Time.now.to_f
    obj.credit_line_name = credit_line.name
    obj.credit_line_anual_rate = credit_line.anual_rate
  end
  after_create :queue

  def queue
    CreditQueue.send_credit(self)
  end

  def credit_line
    @credit_line||=CreditLine.find(self.credit_line_id)
  end

  def generate_payment_plan
    self.risk= self.calculate_risk
    self.create_payments
    self.state = 'done'
    self.save!    
  end

  def create_payments
    self.payments=[]
    monthly_payment = self.get_monthly_payment
    self.total_payment= monthly_payment*self.months
    self.total_interest = self.total_payment-self.amount
    balance = self.amount
    self.months.times do |index|
      self.payments<<{}.tap do |hash|
        hash[:number] = index+1
        hash[:payment]=monthly_payment
        hash[:interest]= interest = balance * self.monthly_rate
        hash[:balance] = balance = balance + interest - monthly_payment
        hash[:amortization] =  monthly_payment - interest
      end
    end
  end

  def get_monthly_payment
    @get_monthly_payment||=(self.amount / ((1-(1+self.monthly_rate)**(self.months*-1.0))/self.monthly_rate))
  end
  
  #Tasa efectiva mensual
  def monthly_rate
    @monthly_rate ||= ((1.0+(self.credit_line_anual_rate.to_f/100.0))**(1.0/self.months.to_i))-1.0
  end

  def calculate_risk
    time = Time.now+25.seconds
    index=0
    while time > Time.now do 
      SecureRandom.base64(10000000)[0..10]
      index+=1
    end
    Credit.logger.info("Executed #{index}")
    (Random.rand*11).to_i
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_model, only: [ :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :edit]
  skip_before_action :verify_authenticity_token
  helper_method :get_credit_lines

  respond_to :html

  def new
    @company = Company.where(url: params[:url]).first
    @object = Credit.new
    @object.url = @company.url
  end

  def edit
    
  end

  def create
    @object= Credit.new(get_params)
    if @object.save
      session[:credit_id]=@object.id
      redirect_to credit_path(1)
    else
      render 'new'
    end
  end

  def show
    @object = Credit.find(session[:credit_id])
  end

  def index
    @count=Credit.where(url: current_company_url).count

    unless params[:next]
      session.delete(:credit_pagination_milestones)
      @collection = Credit.where(url: current_company_url).limit(50)
    else
      session[:credit_pagination_milestones]||=[]
      session[:credit_pagination_milestones]<<  params[:next] unless(session[:credit_pagination_milestones].include?(params[:next]))
      milestone=Credit.find(params[:next])
      @collection = Credit.where(url: current_company_url).start(milestone).limit(50)
    end
  end

  protected
  def get_credit_lines
    @credit_lines||=CreditLine.where(url: @object.url).where(state: 'active').all
  end

  def get_params
    params.require(:credit).permit(:identification,:amount, 
        :months, :credit_line_id,:url ).update({birthday: 
          Date.new(params.require(:credit)["birthday(1i)"].to_i,
            params.require(:credit)["birthday(2i)"].to_i,
            params.require(:credit)["birthday(3i)"].to_i)})

    end

  def set_model
    @object = Credit.find(params[:id])
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/edit.html.erb
<div class="page-header">
  <h1>Datos del crédito</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Identificacion:</strong></dt>
  <dd><%= @object.identification %>   <%= @object.id.to_s %></dd>
  <dt><strong>Fecha de nacimiento:</strong></dt>
  <dd><%= l @object.birthday.to_date %></dd>
  <dt><strong>Valor del crédito:</strong></dt>
  <dd><%= number_to_currency @object.amount %></dd>
  <dt><strong>Linea de crédito:</strong></dt>
  <dd><%= @object.credit_line_name %></dd>
  <dt><strong>Plazo en meses:</strong></dt>
  <dd><%= @object.months %></dd>
  <dt><strong>Estado:</strong></dt>
  <dd id="estado" title='<%= @object.state%>'>
    <%  if @object.state == 'done' %>
      <%= 'Generado'  %>
    <% elsif @object.state == 'pending' %>
      Pendiente
      <%=  image_tag( 'spinner.gif', style: "width: 32 px; height: 32px", id: 'cliente_calculando') %>
    <% else %>
      Error
    <% end %>
 </dd>
  <% if @object.state == 'done' %>
    
    <dt><strong>Riesgo:</strong></dt>
    <dd><%= @object.risk %></dd>
    <dt><strong>Valor total a pagar:</strong></dt>
    <dd><%= number_to_currency @object.total_payment %></dd>
    <dt><strong>Valor total intereses:</strong></dt>
    <dd><%= number_to_currency @object.total_interest %></dd>
    <table class='table' style='text-align: right'>
      <thead>
        <thead style='text-align: right'>
          <th>Número</th>
          <th style='text-align: right'>Interés</th>
          <th style='text-align: right'>Amortización</th>
          <th style='text-align: right'>Pago cuota</th>
          <th style='text-align: right'>Saldo</th>


        </thead>
        <tbody class='table-striped'>
          <% @object.payments.each do |payment|%>
          <tr>
            <td>
              <%= payment['number'] %>
            </td>
            <td>
              <%= number_to_currency payment['interest'] %>
              
            </td>
            <td>
              <%= number_to_currency payment['amortization'] %>
              
            </td>
            <td>
              <%= number_to_currency payment['payment'] %>
              
            </td>
            <td>
              <%= number_to_currency payment['balance'] %>
              
            </td>
          </tr>
          <% end %>
        </tbody>
    </table>
  <% end%>
</dl>

<%= link_to 'Volver', credits_path(), 
  :class => 'btn btn-default' %>

app/views/credits/index.html.erb
<div class="page-header">
  <h1>Créditos</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Identificacion</th>
      <th>Valor</th>
      <th>Plazo</th>
      <th>Linea</th>
      <th>Estado</th>
      <th>Riesgo</th>
      <th>Fecha</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id='list'>
    <% @collection.each do |item| %>
      <tr data-id="<%= item.id-%>">
        <td><%= link_to(truncate(item.id.to_s,length: 11), edit_credit_path(item), title: item.id ) %></td>
        <td><%=  item.identification%></td>
        <td><%= number_to_currency item.amount %></td>
        <td><%= item.months %></td>
        <td><%= item.credit_line_name %></td>
        <td><%= item.state %></td>
        <td><%= item.risk if item.state == 'done' %></td>
        <td><%= l(item.created_at) %></td>
        <td>
          <%= link_to "Ver detalles",
                      edit_credit_path(item), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to("1", credits_path()) if !session[:credit_pagination_milestones].blank?%>

<% (session[:credit_pagination_milestones]||[]).each_with_index do |milestone, index| %>
  <%= link_to((index+2), credits_path(next: milestone))%>

<% end %>
<%= link_to('Siguiente>>', credits_path(next: @collection.last.id)) if @collection.last && @count> 50%>
Encontrados <%= @count%> registros aproximadamente.

app/views/credits/new.html.erb
<div class="page-header">
  <h1> Registro de crédito</h1>
</div>

<%= simple_form_for(@object) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :identification%>
    <%= f.input :birthday, as: :date,  :start_year => Date.today.year - 80%>
    <%= f.input :amount%>
    <%= f.input :months%>
    <%= f.input :url, as: :hidden%>
    <%= f.input( :credit_line_id, collection: get_credit_lines)%>
  </div>

  <div class="form-actions">
    <%= f.button(:submit) %>
    <%= bs_button_to t(:cancel), credits_path,
      style: "inverse" %>
  </div>
<% end %>

app/views/credits/show.html.erb
<div class="page-header">
  <h1>Datos del crédito</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Identificacion:</strong></dt>
  <dd title='<%= @object.id %>'><%= @object.identification %> </dd>
  <dt><strong>Fecha de nacimiento:</strong></dt>
  <dd><%= l @object.birthday.to_date %></dd>
  <dt><strong>Valor del crédito:</strong></dt>
  <dd><%= number_to_currency @object.amount %></dd>
  <dt><strong>Linea de crédito:</strong></dt>
  <dd><%= @object.credit_line_name %></dd>
  <dt><strong>Plazo en meses:</strong></dt>
  <dd><%= @object.months %></dd>
  <dt><strong>Estado:</strong></dt>
  <dd id="estado" title='<%= @object.state%>'>
    <%  if @object.state == 'done' %>
      <%= 'Generado'  %>
    <% elsif @object.state == 'pending' %>
      Pendiente
      <%=  image_tag( 'spinner.gif', style: "width: 32 px; height: 32px", id: 'cliente_calculando') %>
    <% else %>
      Error
    <% end %>
 </dd>
  <% if @object.state == 'done' %>
    
    <dt><strong>Riesgo:</strong></dt>
    <dd><%= @object.risk %></dd>
    <dt><strong>Valor total a pagar:</strong></dt>
    <dd><%= number_to_currency @object.total_payment %></dd>
    <dt><strong>Valor total intereses:</strong></dt>
    <dd><%= number_to_currency @object.total_interest %></dd>
    <table class='table' style='text-align: right'>
      <thead>
        <thead style='text-align: right'>
          <th>Número</th>
          <th style='text-align: right'>Interés</th>
          <th style='text-align: right'>Amortización</th>
          <th style='text-align: right'>Pago cuota</th>
          <th style='text-align: right'>Saldo</th>


        </thead>
        <tbody class='table-striped'>
          <% @object.payments.each do |payment|%>
          <tr>
            <td>
              <%= payment["number"] %>
            </td>
            <td>
              <%= number_to_currency payment["interest"] %>
              
            </td>
            <td>
              <%= number_to_currency payment["amortization"] %>
              
            </td>
            <td>
              <%= number_to_currency payment["payment"] %>
              
            </td>
            <td>
              <%= number_to_currency payment["balance"] %>
              
            </td>
          </tr>
          <% end %>
        </tbody>
    </table>
  <% end%>
</dl>

<%= link_to 'Actualizar', credit_path(1), 
  :class => 'btn btn-default' unless @object.state=='done'%>