config/routes.rb
Rails.application.routes.draw do
  resource :companies 
  resource :company_session 
  put 'credit_lines/:id' => 'credit_lines#update'
  resources :credit_lines

  resources :credits 
  get 'company/:url/signup' => "credits#new"  

  root to: 'start#index'

  resources :clientes
  get 'empresa/:empresa_url/signup' => "clientes#new"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SimuladoresDeCredito" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SimuladoresDeCredito</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            
            <% if admin_signed_in? %>
            
            <li>
              <%= link_to "Cerrar sesión: #{current_admin_email}",company_session_path,  method: :delete  %>
            </li>
            <li>
              <label style='padding-top: 15px'>URL: <%="http://#{request.host}/company/#{current_company_url}/signup"%></label>
              
            </li>
            <% else %>
            <li>
              <%= link_to "Crear cuenta", new_companies_path  %>
            </li>
            <li>
              <%= link_to "Iniciar sesión", new_company_session_path  %>
            </li>
            <% end %>
          </li>
          
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      <div class="col-lg-3">
        <% if admin_signed_in? %>
        <div class="well sidebar-nav">
          
          <h3></h3>
          <ul class="nav nav-list">
            <li><%= link_to "Lineas de crédito", credit_lines_path  %></li>
            <li><%= link_to "Planes de pago generados", credits_path  %></li>
          </ul>
          
          </div><!--/.well -->
          <% end %>
          </div><!--/span-->
          </div><!--/row-->
          <footer>
            <p>&copy; Simuladores de Crédito Company 2014</p>
          </footer>
          </div> <!-- /container -->
        </body>
      </html>